drop database if exists projeto_psicologia;
create database projeto_psicologia;
USE projeto_psicologia;

CREATE TABLE GRUPO (
    ID CHAR(36) PRIMARY KEY,
    NOME VARCHAR(70)
);

CREATE TABLE TEMA(
    COD_TEMA INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100),
    REFLEXAO VARCHAR(10000)
);

CREATE TABLE USUARIO(
    ID CHAR(36) PRIMARY KEY,
    LOGIN VARCHAR(100),
    SENHA VARCHAR(20),
    NOME VARCHAR(70),
    CPF VARCHAR(11),
    CNPJ VARCHAR(14),
    RG VARCHAR(9),
    EMAIL VARCHAR(70),
    ENDERECO VARCHAR(70),
    CIDADE VARCHAR(70),
    BAIRRO VARCHAR(70),
    UF VARCHAR (2),
    CEP VARCHAR(8),
    COMPLEMENTO VARCHAR(70),
    DATA_NASCIMENTO DATE,
    TELEFONE VARCHAR(20),
    CELULAR VARCHAR(20),
    PROFISSAO VARCHAR(20),
    CAMINHO_FOTO VARCHAR(20),
    CRM VARCHAR(50),
    CRP VARCHAR(50),
    OBSERVACAO VARCHAR(500),
    TIPO VARCHAR(20),
    TEMA_ID INT,
    FOREIGN KEY (TEMA_ID) REFERENCES TEMA(COD_TEMA)
);

CREATE TABLE GRUPOUSUARIO (
    ID CHAR(36) PRIMARY KEY,
    ID_USUARIO CHAR(36),
    ID_GRUPO CHAR(36),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
    FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO(ID)
);


